"""initial schema

Revision ID: d1adbfc91c1e
Revises: 
Create Date: 2026-06-22 14:46:28.568670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1adbfc91c1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('wallet_score', sa.Float(), nullable=True),
    sa.Column('token_score', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_traded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_alerts_signature'), 'alerts', ['signature'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_table('live_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('sol_amount', sa.Float(), nullable=False),
    sa.Column('token_amount', sa.Float(), nullable=False),
    sa.Column('price_sol', sa.Float(), nullable=False),
    sa.Column('fee_sol', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('realized_pnl_sol', sa.Float(), nullable=False),
    sa.Column('source_signature', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_trades_created_at'), 'live_trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_live_trades_is_open'), 'live_trades', ['is_open'], unique=False)
    op.create_index(op.f('ix_live_trades_token_mint'), 'live_trades', ['token_mint'], unique=False)
    op.create_index(op.f('ix_live_trades_wallet_address'), 'live_trades', ['wallet_address'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('sol_amount', sa.Float(), nullable=False),
    sa.Column('token_amount', sa.Float(), nullable=False),
    sa.Column('price_sol', sa.Float(), nullable=False),
    sa.Column('fee_sol', sa.Float(), nullable=False),
    sa.Column('slippage_est', sa.Float(), nullable=False),
    sa.Column('realized_pnl_sol', sa.Float(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('source_signature', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_created_at'), 'paper_trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trades_is_open'), 'paper_trades', ['is_open'], unique=False)
    op.create_index(op.f('ix_paper_trades_token_mint'), 'paper_trades', ['token_mint'], unique=False)
    op.create_index(op.f('ix_paper_trades_wallet_address'), 'paper_trades', ['wallet_address'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('qty_open', sa.Float(), nullable=False),
    sa.Column('cost_basis_sol', sa.Float(), nullable=False),
    sa.Column('realized_pnl_sol', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_sol', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hold_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_is_open'), 'positions', ['is_open'], unique=False)
    op.create_index(op.f('ix_positions_token_mint'), 'positions', ['token_mint'], unique=False)
    op.create_index(op.f('ix_positions_wallet_address'), 'positions', ['wallet_address'], unique=False)
    op.create_table('risk_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('sol_amount', sa.Float(), nullable=False),
    sa.Column('token_amount', sa.Float(), nullable=False),
    sa.Column('price_sol', sa.Float(), nullable=False),
    sa.Column('fee_sol', sa.Float(), nullable=False),
    sa.Column('slippage_est', sa.Float(), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=True),
    sa.Column('block_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('confirmation', sa.String(length=16), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_swap_wallet_token', 'swaps', ['wallet_address', 'token_mint'], unique=False)
    op.create_index(op.f('ix_swaps_block_time'), 'swaps', ['block_time'], unique=False)
    op.create_index(op.f('ix_swaps_signature'), 'swaps', ['signature'], unique=True)
    op.create_index(op.f('ix_swaps_token_mint'), 'swaps', ['token_mint'], unique=False)
    op.create_index(op.f('ix_swaps_wallet_address'), 'swaps', ['wallet_address'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_on_chain_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_creator'), 'tokens', ['creator'], unique=False)
    op.create_index(op.f('ix_tokens_latest_score'), 'tokens', ['latest_score'], unique=False)
    op.create_index(op.f('ix_tokens_mint'), 'tokens', ['mint'], unique=True)
    op.create_index(op.f('ix_tokens_stage'), 'tokens', ['stage'], unique=False)
    op.create_index(op.f('ix_tokens_status'), 'tokens', ['status'], unique=False)
    op.create_table('wallet_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_address', sa.String(length=64), nullable=False),
    sa.Column('target_address', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_address', 'target_address', 'kind', name='uq_wallet_rel')
    )
    op.create_index(op.f('ix_wallet_relationships_source_address'), 'wallet_relationships', ['source_address'], unique=False)
    op.create_index(op.f('ix_wallet_relationships_target_address'), 'wallet_relationships', ['target_address'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('discovery_source', sa.String(length=64), nullable=True),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_latest_score'), 'wallets', ['latest_score'], unique=False)
    op.create_index(op.f('ix_wallets_status'), 'wallets', ['status'], unique=False)
    op.create_table('token_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_insider', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'address', name='uq_token_holder')
    )
    op.create_index(op.f('ix_token_holders_address'), 'token_holders', ['address'], unique=False)
    op.create_index(op.f('ix_token_holders_token_id'), 'token_holders', ['token_id'], unique=False)
    op.create_table('token_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('security', sa.Float(), nullable=False),
    sa.Column('holder_distribution', sa.Float(), nullable=False),
    sa.Column('creator_history', sa.Float(), nullable=False),
    sa.Column('liquidity_quality', sa.Float(), nullable=False),
    sa.Column('organic_growth', sa.Float(), nullable=False),
    sa.Column('trade_behavior', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('vetoed', sa.Boolean(), nullable=False),
    sa.Column('veto_reasons', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_scores_created_at'), 'token_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_scores_token_id'), 'token_scores', ['token_id'], unique=False)
    op.create_table('wallet_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('organic', sa.Float(), nullable=False),
    sa.Column('hold_quality', sa.Float(), nullable=False),
    sa.Column('safety', sa.Float(), nullable=False),
    sa.Column('recency', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('vetoed', sa.Boolean(), nullable=False),
    sa.Column('veto_reasons', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_scores_created_at'), 'wallet_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_scores_wallet_id'), 'wallet_scores', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_scores_wallet_id'), table_name='wallet_scores')
    op.drop_index(op.f('ix_wallet_scores_created_at'), table_name='wallet_scores')
    op.drop_table('wallet_scores')
    op.drop_index(op.f('ix_token_scores_token_id'), table_name='token_scores')
    op.drop_index(op.f('ix_token_scores_created_at'), table_name='token_scores')
    op.drop_table('token_scores')
    op.drop_index(op.f('ix_token_holders_token_id'), table_name='token_holders')
    op.drop_index(op.f('ix_token_holders_address'), table_name='token_holders')
    op.drop_table('token_holders')
    op.drop_index(op.f('ix_wallets_status'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_latest_score'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_wallet_relationships_target_address'), table_name='wallet_relationships')
    op.drop_index(op.f('ix_wallet_relationships_source_address'), table_name='wallet_relationships')
    op.drop_table('wallet_relationships')
    op.drop_index(op.f('ix_tokens_status'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_stage'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_mint'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_latest_score'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_creator'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_swaps_wallet_address'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_token_mint'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_signature'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_block_time'), table_name='swaps')
    op.drop_index('ix_swap_wallet_token', table_name='swaps')
    op.drop_table('swaps')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_positions_wallet_address'), table_name='positions')
    op.drop_index(op.f('ix_positions_token_mint'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_open'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_paper_trades_wallet_address'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_token_mint'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_is_open'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_created_at'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_live_trades_wallet_address'), table_name='live_trades')
    op.drop_index(op.f('ix_live_trades_token_mint'), table_name='live_trades')
    op.drop_index(op.f('ix_live_trades_is_open'), table_name='live_trades')
    op.drop_index(op.f('ix_live_trades_created_at'), table_name='live_trades')
    op.drop_table('live_trades')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_signature'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
